version: "3.1"

services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
    - "db-data:/var/lib/postgresql/data"
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: judgeless

  app:
    build: .
    restart: always
    env_file:
      - .env.local
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/judgeless
    links: [ db ]
    ports:
    - "3000:3000"

volumes:
  db-data:
    driver: local
