# Sample values for judgeless.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: sandipndev/judgeless

podAnnotations: {}

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
