name: Build & Push to GCR
on:
  push:
    branches: [main]
    paths:
      - "scripts/startup.sh"
      - "!.github/**"
      - "!terraform/**"
      - "!charts/**"
      - "!scripts/**"
      - "!.env.local.example"
      - "!.gitignore"
      - "!docker-compose.yml"
      - "!Makefile"
      - "!README.md"
  workflow_dispatch:

jobs:
  build: 
    name: Build & Push to GCR
    runs-on: ubuntu-latest

    env:
      HASH: $(git rev-parse --short "$GITHUB_SHA")
      BRANCH: ${GITHUB_REF##*/}
      SERVICE_NAME: ${{ secrets.NAME_PREFIX }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}

    steps:
      - uses: actions/checkout@v2

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCR_SA_CREDS }}
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true

      - name: Build
        run: |
          cat <<EOF > .env.local

          # Firebase WebApp
          NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY="${{ secrets.NEXT_PUBLIC_FIREBASE_PUBLIC_API_KEY }}"
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${{ secrets.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN }}"
          NEXT_PUBLIC_FIREBASE_DATABASE_URL="${{ secrets.NEXT_PUBLIC_FIREBASE_DATABASE_URL }}"
          NEXT_PUBLIC_FIREBASE_PROJECT_ID="${{ secrets.NEXT_PUBLIC_FIREBASE_PROJECT_ID }}"

          # Firebase Admin
          FIREBASE_CLIENT_EMAIL=""
          # Private Key must be wrapped in quotes(") and parsed using JSON.parse
          # on the app itself. This is because of the way Vercel stores env variables.
          # Refer: https://github.com/vercel/vercel/issues/749#issuecomment-707515089
          FIREBASE_PRIVATE_KEY='""'

          # Secrets used to sign cookies
          COOKIE_SECRET_CURRENT=""
          COOKIE_SECRET_PREVIOUS=""

          # Cookie options
          NEXT_PUBLIC_COOKIE_SECURE=${{ secrets.NEXT_PUBLIC_COOKIE_SECURE }}

          # Database
          DATABASE_URL=""

          EOF

          docker build -t us.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA .

      - name: Push
        run: |
          gcloud auth configure-docker -q
          docker push us.gcr.io/$PROJECT_ID/$SERVICE_NAME:$GITHUB_SHA
