name: Deploy
on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy
        run: |
          cd terraform/env/prod

          cat <<EOF > inception-sa-creds.json
          ${{ secrets.INCEPTION_SA_CREDS }}
          EOF

          export GOOGLE_CREDENTIALS=$(cat inception-sa-creds.json)

          cat <<EOF > bootstrap/terraform.tfvars
          gcp_project = "${{ secrets.GCP_PROJECT }}"
          name_prefix = "${{ secrets.NAME_PREFIX }}"
          EOF

          pushd bootstrap
          terraform init
          terraform refresh
          popd

          make prep-inception USERS=${{ secrets.USERS_ARRAY }} INCEPTION_EMAIL=${{ secrets.INCEPTION_EMAIL }}

          echo yes | make inception
          echo yes | make prep-platform
          echo yes | make platform
          echo yes | make services
